In [37]:
from sklearn.preprocessing import StandardScaler

In [38]:
data = [[-1,2],[-0.5,6],[0,8],[1,18]]

【原始套件】
此作業要模仿部分: StandardScaler

In [39]:
scaler  =  StandardScaler ()

In [40]:
#----fit----
scaler.fit(data)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [41]:
# mean_  對向量 做平均
scaler.mean_

array([-0.125,  8.5  ])

In [42]:
# var_   對向量 做變異數# var_  
scaler.var_

array([  0.546875,  34.75    ])

In [43]:
#----transform---- 對向量 做標準差
scaler.transform(data)

array([[-1.18321596, -1.10264561],
       [-0.50709255, -0.42409446],
       [ 0.16903085, -0.08481889],
       [ 1.52127766,  1.61155897]])

In [44]:
scaler.transform([[2,2]])

array([[ 2.87352447, -1.10264561]])

In [16]:
import numpy as np

【模擬】
試算類別中的 fit、transform，找出原計算方式

In [17]:
# fit--找scaler.mean_的原理
np.mean(data, axis=0)

array([-0.125,  9.   ])

In [18]:
#  fit--找scaler.var_的原理
np.var(data, axis=0)

array([  0.546875,  35.      ])

In [19]:
# transform--找scaler.transform的原理調。 做成變異數
(np.array(data) - scaler.mean_ ) / (scaler.var_**0.5)

array([[-1.18321596, -1.18321596],
       [-0.50709255, -0.50709255],
       [ 0.16903085,  0.16903085],
       [ 1.52127766,  1.52127766]])

In [20]:
class MyStandardScaler: # 【　MyStandardScaler 此類別有以下功能　】 
    
    def __init__(self):                             #初始化定義
        self.mean = None
        self.var = None
        
    def fit(self,data):                            #self:慣例上，第一個傳self  #第二個傳data
        self.mean = np.mean(data, axis=0)
        self.var  = np.var(data, axis=0)
        
    def transform(self,data):
        return (np.array(data) - scaler.mean_ ) / (scaler.var_**0.5)
    
    def fit_transform(self,data):
        self.fit(data)
        return self.transform(data)

【測試模擬結果】

In [25]:
myscaler = MyStandardScaler()

In [26]:
myscaler.fit(data)

In [28]:
myscaler.mean

array([-0.125,  9.   ])

In [29]:
myscaler.var

array([  0.546875,  35.      ])

In [30]:
myscaler.transform(data)

array([[-1.18321596, -1.18321596],
       [-0.50709255, -0.50709255],
       [ 0.16903085,  0.16903085],
       [ 1.52127766,  1.52127766]])

In [31]:
myscaler.transform([[2,2]])

array([[ 2.87352447, -1.18321596]])